project:
  type: website

# Top navigation bar
website:
  title: "model_auto_interpret"
  description: "Machine Learning Model Interpretation and Hyperparameter Tuning"
  navbar:
    left:
      - text: "Home"
        file: index.qmd        
      - text: "Tutorial"
        file: tutorial.qmd      
      - text: "API Reference"
        file: reference/index.qmd
    right:
      - icon: github
        href: https://github.com/UBC-MDS/model_interpretation

# tell quarto to read the generated sidebar
metadata-files:
  - reference/_sidebar.yml

# tell quarto to read the generated styles
format:
  html:
    css:
      - reference/_styles-quartodoc.css

quartodoc:
  # the name used to import the package you want to create reference docs for
  package: model_auto_interpret

  # write sidebar and style data
  sidebar: reference/_sidebar.yml
  css: reference/_styles-quartodoc.css

  sections:
    - title: Model Interpretation Methods
      desc: Functions to help interpret machine learning models.
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - hyperparameter_tuning_summary.param_tuning_summary
        - model_compare.model_cv_metric_compare
        - model_evaluation.model_evaluation_plotting
